package org.reactome.restfulapi.models;

// Generated Jul 8, 2011 1:48:55 PM by Hibernate Tools 3.4.0.CR1

import javax.xml.bind.annotation.XmlRootElement;

/**
 * GenomeEncodedEntity generated by hbm2java
 */
@XmlRootElement
public class GenomeEncodedEntity extends org.reactome.restfulapi.models.PhysicalEntity {
    private Species species;

    public GenomeEncodedEntity() {
    }

    public Species getSpecies() {
        return species;
    }

    public void setSpecies(Species species) {
        this.species = species;
    }


}
