package org.reactome.restfulapi.models;

import javax.xml.bind.annotation.XmlRootElement;

// Generated Jul 8, 2011 1:48:55 PM by Hibernate Tools 3.4.0.CR1

/**
 * PathwayDiagram generated by hbm2java
 */
@XmlRootElement
public class PathwayDiagram extends PathwayDiagramItem {

    private Integer height;
    private Pathway representedPathway;
    private String storedAtxml;
    private Integer width;

    public PathwayDiagram() {
    }

    public Integer getHeight() {
        return this.height;
    }

    public void setHeight(Integer height) {
        this.height = height;
    }

    public Pathway getRepresentedPathway() {
        return this.representedPathway;
    }

    public void setRepresentedPathway(Pathway representedPathway) {
        this.representedPathway = representedPathway;
    }

    public String getStoredAtxml() {
        return this.storedAtxml;
    }

    public void setStoredAtxml(String storedAtxml) {
        this.storedAtxml = storedAtxml;
    }

    public Integer getWidth() {
        return this.width;
    }

    public void setWidth(Integer width) {
        this.width = width;
    }

}
