package org.reactome.restfulapi.models;

// Generated Jul 8, 2011 1:48:55 PM by Hibernate Tools 3.4.0.CR1

import javax.xml.bind.annotation.XmlRootElement;

/**
 * PsiMod generated by hbm2java
 */
@XmlRootElement
public class PsiMod extends DatabaseObject {

    private String definition;
    private String identifier;
    private String name;
    private Integer referenceDatabase;

    public PsiMod() {
    }

    public String getDefinition() {
        return this.definition;
    }

    public void setDefinition(String definition) {
        this.definition = definition;
    }

    public String getIdentifier() {
        return this.identifier;
    }

    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getReferenceDatabase() {
        return this.referenceDatabase;
    }

    public void setReferenceDatabase(Integer referenceDatabase) {
        this.referenceDatabase = referenceDatabase;
    }

}
