package org.reactome.restfulapi.models;

// Generated Jul 8, 2011 1:48:55 PM by Hibernate Tools 3.4.0.CR1

/**
 * ReferenceGroupCount generated by hbm2java
 */
public class ReferenceGroupCount implements java.io.Serializable {

    private int dbId;
    private Integer maxCount;
    private Integer minCount;
    private Integer referenceGroup;
    private String referenceGroupClass;

    public ReferenceGroupCount() {
    }

    public ReferenceGroupCount(int dbId) {
        this.dbId = dbId;
    }

    public ReferenceGroupCount(int dbId, Integer maxCount, Integer minCount,
                               Integer referenceGroup, String referenceGroupClass) {
        this.dbId = dbId;
        this.maxCount = maxCount;
        this.minCount = minCount;
        this.referenceGroup = referenceGroup;
        this.referenceGroupClass = referenceGroupClass;
    }

    public int getDbId() {
        return this.dbId;
    }

    public void setDbId(int dbId) {
        this.dbId = dbId;
    }

    public Integer getMaxCount() {
        return this.maxCount;
    }

    public void setMaxCount(Integer maxCount) {
        this.maxCount = maxCount;
    }

    public Integer getMinCount() {
        return this.minCount;
    }

    public void setMinCount(Integer minCount) {
        this.minCount = minCount;
    }

    public Integer getReferenceGroup() {
        return this.referenceGroup;
    }

    public void setReferenceGroup(Integer referenceGroup) {
        this.referenceGroup = referenceGroup;
    }

    public String getReferenceGroupClass() {
        return this.referenceGroupClass;
    }

    public void setReferenceGroupClass(String referenceGroupClass) {
        this.referenceGroupClass = referenceGroupClass;
    }

}
