package org.reactome.restfulapi.models;

// Generated Jul 8, 2011 1:48:55 PM by Hibernate Tools 3.4.0.CR1

import javax.xml.bind.annotation.XmlRootElement;
import java.util.Date;

/**
 * Regulation generated by hbm2java
 */
@XmlRootElement
public class Regulation extends DatabaseObject {

    private Integer authored;
    private String authoredClass;
    private DatabaseObject regulatedEntity;
    private String regulatedEntityClass;
    private RegulationType regulationType;
    private String regulationTypeClass;
    private String regulatorClass;
    private Date releaseDate;
    private DatabaseObject regulator;
    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }


    public Regulation() {
    }

    public Integer getAuthored() {
        return this.authored;
    }

    public void setAuthored(Integer authored) {
        this.authored = authored;
    }

    public String getAuthoredClass() {
        return this.authoredClass;
    }

    public void setAuthoredClass(String authoredClass) {
        this.authoredClass = authoredClass;
    }

    public DatabaseObject getRegulatedEntity() {
        return this.regulatedEntity;
    }

    public void setRegulatedEntity(DatabaseObject regulatedEntity) {
        try
        {
            if(regulatedEntity instanceof Event || regulatedEntity instanceof CatalystActivity)
            {
                this.regulatedEntity = regulatedEntity;
            }
            else
                throw new ClassCastException("This class is not allowed:"+ regulatedEntity.getClass());
        }
        catch(ClassCastException e)
        {
            e.printStackTrace();
        }
    }

    public String getRegulatedEntityClass() {
        return this.regulatedEntityClass;
    }

    public void setRegulatedEntityClass(String regulatedEntityClass) {
        this.regulatedEntityClass = regulatedEntityClass;
    }

    public RegulationType getRegulationType() {
        return this.regulationType;
    }

    public void setRegulationType(RegulationType regulationType) {

        this.regulationType = regulationType;
    }

    public String getRegulationTypeClass() {
        return this.regulationTypeClass;
    }

    public void setRegulationTypeClass(String regulationTypeClass) {
        this.regulationTypeClass = regulationTypeClass;
    }

    public DatabaseObject getRegulator() {
        return this.regulator;
    }

    public void setRegulator(DatabaseObject regulator) {
        try
        {
            if(regulator instanceof Event || regulator instanceof CatalystActivity ||
                    regulator instanceof PhysicalEntity)
            {
                this.regulator = regulator;
            }
            else
                throw new ClassCastException("This class is not allowed:"+ regulator.getClass());
        }
        catch(ClassCastException e)
        {
            e.printStackTrace();
        }
    }

    public String getRegulatorClass() {
        return this.regulatorClass;
    }

    public void setRegulatorClass(String regulatorClass) {
        this.regulatorClass = regulatorClass;
    }

    public Date getReleaseDate() {
        return this.releaseDate;
    }

    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }

}
