package org.reactome.restfulapi.models;

// Generated Jul 8, 2011 1:48:55 PM by Hibernate Tools 3.4.0.CR1

import javax.xml.bind.annotation.XmlRootElement;

/**
 * SequenceDomain generated by hbm2java
 */
@XmlRootElement
public class SequenceDomain extends DatabaseObject {

    private Integer endCoordinate;
    private Integer referenceEntity;
    private String referenceEntityClass;
    private Integer startCoordinate;

    public SequenceDomain() {
    }

    public Integer getEndCoordinate() {
        return this.endCoordinate;
    }

    public void setEndCoordinate(Integer endCoordinate) {
        this.endCoordinate = endCoordinate;
    }

    public Integer getReferenceEntity() {
        return this.referenceEntity;
    }

    public void setReferenceEntity(Integer referenceEntity) {
        this.referenceEntity = referenceEntity;
    }

    public String getReferenceEntityClass() {
        return this.referenceEntityClass;
    }

    public void setReferenceEntityClass(String referenceEntityClass) {
        this.referenceEntityClass = referenceEntityClass;
    }

    public Integer getStartCoordinate() {
        return this.startCoordinate;
    }

    public void setStartCoordinate(Integer startCoordinate) {
        this.startCoordinate = startCoordinate;
    }

}
