package org.reactome.restfulapi.models;

import java.util.List;

import javax.xml.bind.annotation.XmlRootElement;

// Generated Jul 8, 2011 1:48:55 PM by Hibernate Tools 3.4.0.CR1

/**
 * SimpleEntity generated by hbm2java
 */
@XmlRootElement
public class SimpleEntity extends PhysicalEntity {
    private List<ReferenceMolecule> referenceEntity;
    private Species species;

    public SimpleEntity() {
    }

    public List<ReferenceMolecule> getReferenceEntity() {
        return referenceEntity;
    }

    public void setReferenceEntity(List<ReferenceMolecule> referenceEntity) {
        this.referenceEntity = referenceEntity;
    }

    public Species getSpecies() {
        return species;
    }

    public void setSpecies(Species species) {
        this.species = species;
    }

}
