package org.reactome.restfulapi.models;

// Generated Jul 8, 2011 1:48:55 PM by Hibernate Tools 3.4.0.CR1

import javax.xml.bind.annotation.XmlRootElement;

/**
 * StableIdentifier generated by hbm2java
 */
@XmlRootElement
public class StableIdentifier extends DatabaseObject {

    private String identifier;
    private String identifierVersion;
    private String oldIdentifier;
    private String oldIdentifierVersion;
    private Boolean released;

    public StableIdentifier() {
    }

    public String getIdentifier() {
        return this.identifier;
    }

    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    public String getIdentifierVersion() {
        return this.identifierVersion;
    }

    public void setIdentifierVersion(String identifierVersion) {
        this.identifierVersion = identifierVersion;
    }

    public String getOldIdentifier() {
        return oldIdentifier;
    }

    public void setOldIdentifier(String oldIdentifier) {
        this.oldIdentifier = oldIdentifier;
    }

    public String getOldIdentifierVersion() {
        return oldIdentifierVersion;
    }

    public void setOldIdentifierVersion(String oldIdentifierVersion) {
        this.oldIdentifierVersion = oldIdentifierVersion;
    }

    public Boolean getReleased() {
        return released;
    }

    public void setReleased(Boolean released) {
        this.released = released;
    }

}
