package org.reactome.restfulapi.models;

import java.util.List;

// Generated Jul 8, 2011 1:48:55 PM by Hibernate Tools 3.4.0.CR1

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Go_CellularComponent generated by hbm2java
 */
@XmlRootElement
public class GO_CellularComponent extends DatabaseObject {

    private String accession;
    private String definition;
    private ReferenceDatabase referenceDatabase;
    private String referenceDatabaseClass;
    private List<GO_CellularComponent> surroundedBy;

    public GO_CellularComponent() {
    }

    public String getAccession() {
        return this.accession;
    }

    public List<GO_CellularComponent> getSurroundedBy() {
        return surroundedBy;
    }

    public void setSurroundedBy(List<GO_CellularComponent> surroundedBy) {
        this.surroundedBy = surroundedBy;
    }

    public void setAccession(String accession) {
        this.accession = accession;
    }

    public String getDefinition() {
        return this.definition;
    }

    public void setDefinition(String definition) {
        this.definition = definition;
    }

    public ReferenceDatabase getReferenceDatabase() {
        return this.referenceDatabase;
    }

    public void setReferenceDatabase(ReferenceDatabase referenceDatabase) {
        this.referenceDatabase = referenceDatabase;
    }

    public String getReferenceDatabaseClass() {
        return this.referenceDatabaseClass;
    }

    public void setReferenceDatabaseClass(String referenceDatabaseClass) {
        this.referenceDatabaseClass = referenceDatabaseClass;
    }
}
